# Archivo de inventario de Ansible
# Aquí se definen los hosts donde se ejecutarán las tareas.

# "localhost" indica que las tareas se aplicarán en la máquina local.
# "ansible_connection=local" especifica que Ansible no usará SSH,
# sino que ejecutará las acciones directamente en el mismo sistema.
localhost ansible_connection=local
