# Definición de un grupo de servidores backend (balanceo de carga)
upstream backend_app {
    server app1:80;   # Primer servidor backend que responde en el puerto 80
    server app2:80;   # Segundo servidor backend en el puerto 80
    server app3:80;   # Tercer servidor backend en el puerto 80
    keepalive 16;     # Mantiene hasta 16 conexiones abiertas para reutilizarlas (mejora el rendimiento)
}

# Configuración principal del servidor NGINX
server {
    listen 80 default_server;  # Escucha en el puerto 80 como servidor por defecto
    server_name _;             # Acepta cualquier nombre de servidor (comodín)

    # Definición de la ruta raíz "/"
    location / {
        proxy_pass http://backend_app;  # Redirige las peticiones al grupo de servidores definido en "upstream"
    }
}
